/********************************************************************
 * Copyright (c) 2026 Contributors to the Eclipse Foundation.
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Data In Motion Consulting - initial implementation
 ********************************************************************/
package org.eclipse.fennec.persistence.test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EStructuralFeature;
import org.eclipse.persistence.config.PersistenceUnitProperties;
import org.eclipse.persistence.descriptors.ClassDescriptor;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import jakarta.persistence.EntityManager;

/**
 * Non-OSGi port of {@code CompositeIdEclipseLinkTest}. Verifies EclipseLink
 * persistence with a composite primary key ({@code MultiPKClass}) against
 * in-memory H2. The schema is generated by EclipseLink's DDL pipeline; seed
 * rows are inserted afterwards via JDBC so that read-back via EclipseLink
 * exercises the composite-key mapping end-to-end.
 */
class NonOsgiCompositeIdEclipseLinkTest extends NonOsgiPersistenceTestBase {

	private static final String MULTI_PK_CLASS = "MultiPKClass";

	private EPackage modelPackage;
	private EClass multiPKClass;
	private String jdbcUrl;

	@BeforeEach
	void setUp() throws Exception {
		modelPackage = loadEcore("data/model.ecore");
		multiPKClass = (EClass) modelPackage.getEClassifier(MULTI_PK_CLASS);
		assertNotNull(multiPKClass);

		jdbcUrl = "jdbc:h2:mem:compositeId_" + UUID.randomUUID() + ";DB_CLOSE_DELAY=-1";
		Map<String, Object> extra = new HashMap<>();
		extra.put(PersistenceUnitProperties.JDBC_URL, jdbcUrl);

		// Schema is generated by EclipseLink via DDL_GENERATION — do not
		// pre-create tables. A broken composite-ID mapping surfaces here first.
		bootstrapPersistence("composite-multi", List.of(multiPKClass), extra);

		seedData();
	}

	private void seedData() throws Exception {
		try (Connection conn = DriverManager.getConnection(jdbcUrl, "sa", "");
			 Statement stmt = conn.createStatement()) {
			stmt.execute("INSERT INTO MULTIPKCLASS (id, timestamp, name) VALUES "
					+ "('key1', '2025-01-01 10:00:00', 'First test record')");
			stmt.execute("INSERT INTO MULTIPKCLASS (id, timestamp, name) VALUES "
					+ "('key2', '2025-01-01 11:00:00', 'Second test record')");
		}
	}

	@Test
	void testMultiPKClassEclipseLinkIntegration() {
		ClassDescriptor descriptor = serverSession.getDescriptorForAlias(multiPKClass.getName());
		assertNotNull(descriptor, "MultiPKClass descriptor should exist");
		assertEquals(2, descriptor.getPrimaryKeyFields().size(),
				"Descriptor should have 2 primary key fields");

		try (EntityManager em = emf.createEntityManager()) {
			var query = em.createQuery("SELECT m FROM " + multiPKClass.getName() + " m");
			List<?> results = query.getResultList();

			assertTrue(results.size() >= 2, "Should find at least 2 seeded records");

			EStructuralFeature idFeature = multiPKClass.getEStructuralFeature("id");
			EStructuralFeature timestampFeature = multiPKClass.getEStructuralFeature("timestamp");

			for (Object result : results) {
				assertTrue(result instanceof EObject, "Should be EObject instance");
				EObject record = (EObject) result;
				assertEquals(multiPKClass, record.eClass());
				assertNotNull(record.eGet(idFeature), "ID component should not be null");
				assertNotNull(record.eGet(timestampFeature), "Timestamp component should not be null");
			}
		}
	}
}
