/********************************************************************
 * Copyright (c) 2026 Contributors to the Eclipse Foundation.
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Data In Motion Consulting - initial implementation
 ********************************************************************/
package org.eclipse.fennec.persistence.test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.emf.ecore.EStructuralFeature;
import org.eclipse.persistence.config.PersistenceUnitProperties;
import org.eclipse.persistence.descriptors.ClassDescriptor;
import org.junit.jupiter.api.Test;

import jakarta.persistence.EntityManager;

/**
 * Non-OSGi port of {@code EPersistenceGltContainmentTest}. Verifies that the
 * OneToMany containment mapping uses a JoinColumn (foreign key on the child
 * table) and not a JoinTable — both when the L2 cache is on and off.
 * <p>
 * Each test seeds a fresh in-memory H2 via JDBC, then runs EclipseLink against
 * the same database through {@link NonOsgiPersistenceTestBase}.
 */
class NonOsgiGltContainmentTest extends NonOsgiPersistenceTestBase {

	private EPackage gltPackage;
	private EClass buildingClass;
	private EClass contactClass;
	private String jdbcUrl;

	private void bootstrapGlt(boolean cacheShared) {
		gltPackage = loadEcore("data/glt/glt.ecore");
		buildingClass = (EClass) gltPackage.getEClassifier("Building");
		contactClass = (EClass) gltPackage.getEClassifier("Contact");
		assertNotNull(buildingClass);
		assertNotNull(contactClass);

		jdbcUrl = "jdbc:h2:mem:glt_" + UUID.randomUUID() + ";DB_CLOSE_DELAY=-1";
		Map<String, Object> props = new HashMap<>();
		props.put(PersistenceUnitProperties.JDBC_URL, jdbcUrl);
		if (!cacheShared) {
			props.put(PersistenceUnitProperties.CACHE_SHARED_DEFAULT, "false");
		}
		// Schema is generated by EclipseLink via DDL_GENERATION (default
		// "create-or-extend-tables") — we do NOT pre-create tables, so that a
		// broken EMF/EclipseLink mapping surfaces as a DDL failure.
		bootstrapPersistence("glt", List.of(buildingClass, contactClass), props);
	}

	/**
	 * Seeds rows into the EclipseLink-generated schema. Must be called
	 * <em>after</em> {@link #bootstrapGlt(boolean)} so the tables exist.
	 */
	private void seedData() throws Exception {
		try (Connection conn = DriverManager.getConnection(jdbcUrl, "sa", "");
			 Statement stmt = conn.createStatement()) {
			stmt.execute("INSERT INTO BUILDINGS (id, city, zip, street) VALUES (100, 'Berlin', 10115, 'Alexanderplatz 1')");
			stmt.execute("INSERT INTO BUILDINGS (id, city, zip, street) VALUES (200, 'Hamburg', 20095, 'Hafenstraße 42')");
			stmt.execute("INSERT INTO CONTACTS (building_id, role, email, phonenumber, first_name, last_name) VALUES "
					+ "(100, 'Hausmeister', 'max.mueller@example.com', '+49-30-12345678', 'Max', 'Mueller')");
			stmt.execute("INSERT INTO CONTACTS (building_id, role, email, phonenumber, first_name, last_name) VALUES "
					+ "(100, 'Owner', 'anna.schmidt@example.com', '+49-30-87654321', 'Anna', 'Schmidt')");
			stmt.execute("INSERT INTO CONTACTS (building_id, role, email, phonenumber, first_name, last_name) VALUES "
					+ "(200, 'Hausmeister', 'hans.fischer@example.com', '+49-40-22222222', 'Hans', 'Fischer')");
		}
	}

	private boolean strictMapping = true;

	@Override
	protected void configureMapper(org.eclipse.fennec.persistence.orm.EntityMapper mapper) {
		mapper.setStrict(strictMapping);
	}

	@Test
	void testGltContainmentWithCache() throws Exception {
		bootstrapGlt(true);
		seedData();
		ClassDescriptor buildingDescriptor = serverSession.getDescriptorForAlias(buildingClass.getName());
		assertNotNull(buildingDescriptor);

		try (EntityManager em = emf.createEntityManager()) {
			EObject building = em.find(buildingDescriptor.getJavaClass(), 100);
			assertNotNull(building, "Should find building with id=100");

			EStructuralFeature contactsFeature = buildingClass.getEStructuralFeature("contacts");
			assertNotNull(contactsFeature);

			Object contacts = building.eGet(contactsFeature);
			assertInstanceOf(List.class, contacts);
			@SuppressWarnings("unchecked")
			List<EObject> contactsList = (List<EObject>) contacts;
			assertEquals(2, contactsList.size(), "Should have 2 contacts for building 100");

			EStructuralFeature roleFeature = contactClass.getEStructuralFeature("role");
			for (EObject contact : contactsList) {
				assertEquals(contactClass, contact.eClass());
				Object role = contact.eGet(roleFeature);
				assertTrue(role.equals("Hausmeister") || role.equals("Owner"),
						"Role should be Hausmeister or Owner, was: " + role);
			}
		}
	}

	@Test
	void testGltContainmentNoCache() throws Exception {
		bootstrapGlt(false);
		seedData();
		ClassDescriptor buildingDescriptor = serverSession.getDescriptorForAlias(buildingClass.getName());
		assertNotNull(buildingDescriptor);

		try (EntityManager em = emf.createEntityManager()) {
			EObject building = em.find(buildingDescriptor.getJavaClass(), 100);
			assertNotNull(building);

			EReference contactsFeature = (EReference) buildingClass.getEStructuralFeature("contacts");
			assertTrue(contactsFeature.isContainment());

			@SuppressWarnings("unchecked")
			List<EObject> contactsList = (List<EObject>) building.eGet(contactsFeature);
			assertNotNull(contactsList);
			assertEquals(2, contactsList.size(), "Should have 2 contacts for building 100 (no cache)");
		}
	}

	@Test
	void testDatabaseSchemaSetup() throws Exception {
		bootstrapGlt(true);
		seedData();

		try (Connection conn = DriverManager.getConnection(jdbcUrl, "sa", "");
			 Statement stmt = conn.createStatement()) {
			try (ResultSet rs = stmt.executeQuery("SELECT COUNT(*) FROM BUILDINGS")) {
				assertTrue(rs.next());
				assertEquals(2, rs.getInt(1));
			}
			try (ResultSet rs = stmt.executeQuery(
					"SELECT building_id, COUNT(*) FROM CONTACTS GROUP BY building_id ORDER BY building_id")) {
				assertTrue(rs.next());
				assertEquals(100, rs.getInt(1));
				assertEquals(2, rs.getInt(2));
				assertTrue(rs.next());
				assertEquals(200, rs.getInt(1));
				assertEquals(1, rs.getInt(2));
			}
		}
	}

	@Test
	void testPersistNewBuildingWithContacts() throws Exception {
		strictMapping = false;
		bootstrapGlt(false);
		seedData();

		ClassDescriptor buildingDescriptor = serverSession.getDescriptorForAlias(buildingClass.getName());
		ClassDescriptor contactDescriptor = serverSession.getDescriptorForAlias(contactClass.getName());
		assertNotNull(buildingDescriptor);
		assertNotNull(contactDescriptor);

		EObject newBuilding = (EObject) buildingDescriptor.getInstantiationPolicy().buildNewInstance();
		EObject contact1 = (EObject) contactDescriptor.getInstantiationPolicy().buildNewInstance();
		EObject contact2 = (EObject) contactDescriptor.getInstantiationPolicy().buildNewInstance();

		EStructuralFeature idFeature = buildingClass.getEStructuralFeature("id");
		EStructuralFeature cityFeature = buildingClass.getEStructuralFeature("city");
		EStructuralFeature zipFeature = buildingClass.getEStructuralFeature("zip");
		EStructuralFeature streetFeature = buildingClass.getEStructuralFeature("street");
		EReference contactsFeature = (EReference) buildingClass.getEStructuralFeature("contacts");

		newBuilding.eSet(idFeature, 300);
		newBuilding.eSet(cityFeature, "Munich");
		newBuilding.eSet(zipFeature, 80331);
		newBuilding.eSet(streetFeature, "Marienplatz 1");

		EStructuralFeature roleFeature = contactClass.getEStructuralFeature("role");
		EStructuralFeature emailFeature = contactClass.getEStructuralFeature("email");
		EStructuralFeature firstNameFeature = contactClass.getEStructuralFeature("firstName");
		EStructuralFeature lastNameFeature = contactClass.getEStructuralFeature("lastName");

		contact1.eSet(roleFeature, "Manager");
		contact1.eSet(emailFeature, "manager@example.com");
		contact1.eSet(firstNameFeature, "John");
		contact1.eSet(lastNameFeature, "Doe");

		contact2.eSet(roleFeature, "Janitor");
		contact2.eSet(emailFeature, "janitor@example.com");
		contact2.eSet(firstNameFeature, "Jane");
		contact2.eSet(lastNameFeature, "Smith");

		@SuppressWarnings("unchecked")
		List<EObject> contacts = (List<EObject>) newBuilding.eGet(contactsFeature);
		contacts.add(contact1);
		contacts.add(contact2);

		try (EntityManager em = emf.createEntityManager()) {
			em.getTransaction().begin();
			em.persist(newBuilding);
			em.getTransaction().commit();
		}

		try (Connection conn = DriverManager.getConnection(jdbcUrl, "sa", "");
			 Statement stmt = conn.createStatement()) {
			try (ResultSet rs = stmt.executeQuery("SELECT COUNT(*) FROM BUILDINGS")) {
				rs.next();
				assertTrue(rs.getInt(1) >= 3, "Should have at least 3 buildings (2 seeded + 1 new)");
			}
			try (ResultSet rs = stmt.executeQuery(
					"SELECT building_id FROM CONTACTS WHERE role IN ('Manager', 'Janitor') ORDER BY role")) {
				int count = 0;
				while (rs.next()) {
					Object bid = rs.getObject("building_id");
					assertNotNull(bid, "new contacts must have their building_id foreign key set");
					assertEquals(300, ((Number) bid).intValue());
					count++;
				}
				assertEquals(2, count, "Should have persisted both new contacts with correct FK");
			}
		}
	}
}
